id: c3a9977046fb4a149070c4a57c01dd81
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_730-Dh%C4%81ra%E1%B9%87%C4%AB_T%C4%81r%C4%81%E2%80%99s_Own_Promise-v2
  language: en
  author: ''
  volume: {}
